services:
  pokemon-postgres:
    image: postgres:16-alpine
    container_name: pokemon-postgres
    restart: always
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
